apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spi-oauth-redirect-proxy-6kvu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rh-ee-abarbaro-tenant/spi-oauth-redirect-proxy/spi-oauth-redirect-proxy-6kvu@sha256:faf3a681d2607ffc64f1d2304eb0ad3f52d538dc73ac6f2e6130103c978990c9
        name: container-image
        resources: {}
status: {}
