apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spi-oauth-redirect-proxy-6kvu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spi-oauth-redirect-proxy-6kvu
    app.kubernetes.io/part-of: spi-oauth-redirect-proxy
  name: spi-oauth-redirect-proxy-6kvu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: spi-oauth-redirect-proxy-6kvu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: spi-oauth-redirect-proxy-6kvu
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 15m
            memory: 69Mi
status: {}
