apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spi-oauth-redirect-proxy-6kvu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spi-oauth-redirect-proxy-6kvu
    app.kubernetes.io/part-of: spi-oauth-redirect-proxy
  name: spi-oauth-redirect-proxy-6kvu
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: spi-oauth-redirect-proxy-6kvu
status:
  loadBalancer: {}
